version: 2

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - examples/hawktui
    - examples/go
    - examples/python
    - examples/nodejs
  exclude-files:
    - ".*_demo\\.go$"
    - "examples/.*"
